### ISSUE TITLE
you acted like an idiot jorge

### ISSUE THREAD

**Issue by ghost** [BSVino/Viewback#2]
shame on you @BSVino . Shame on you for saying the stupidest thing ever in one of your c++ game tutorials regarding this game. In that video about using statistics preventing cheaters in online games, you give an "example" when you mention the statistics part. That example shows how daft and a loser you are. Shame on you for mentioning losers in you garbage example.

Death to your daft mentality. Death to everyone who mentions that stupid word you mentioned. You are a cheap and worthless slave, and so is everyone like you and the idiots you mentioned in your stupid "example". Hope you get punished for that.
Death to "univeristies". Death to every idiot who uses those disgusting words. Death to every idiot who uses disgusting and stupid "titles" when mentioning first names. Death to "health". 

You are not an engineer and will never be one.

**Comment by BSVino** [comment]
I don't plan on dying any time soon. Closed "Won't Do"
